=== cras974/Theory-and-explanatory/Basic programming languages/XML/Ejemplos/cv.dtd
<!ELEMENT cv (nombre,apellidos,direccion,telefono,fax?,email+,idiomas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT idiomas (idioma*)>
<!ELEMENT idioma (#PCDATA)>

=== cras974/Theory-and-explanatory/Basic programming languages/XML/Ejemplos/Cv2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE cv SYSTEM "cv.dtd">
<cv>
    <nombre>Miguel</nombre>
    <apellidos>García Cortés</apellidos>
    <direccion>C/ de arriba nº3</direccion>
    <telefono>958444444</telefono>
    <email>miguel@gmail.com</email>
    <email>miguel2@gmail.com</email>
    <idiomas>
        <idioma>Inglés</idioma>
        <idioma>Francés</idioma>
        <idioma>Chino</idioma>
    </idiomas>
</cv>
