=== cras974/Theory-and-explanatory/Basic programming languages/XML/Ejemplos/Dtd_cv_chulo.dtd
<!ELEMENT cv (nombre,apellidos,f_nac,residencia,contacto,descripcion,competencias,formacion,experiencia-profesional)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT f_nac (#PCDATA)>
<!ELEMENT residencia (ciudad,pais)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT contacto (tlf,correo,linkedin)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT linkedin (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT competencias (competencia+)>
<!ELEMENT competencia (#PCDATA)>
<!ATTLIST competencia nivel (Bajo|Medio|Alto) "Medio">
<!ATTLIST competencia nombre CDATA #REQUIRED>
<!ELEMENT formacion (titulacion+)>
<!ELEMENT titulacion (#PCDATA)>
<!ATTLIST titulacion nombre CDATA #REQUIRED>
<!ATTLIST titulacion centro CDATA #REQUIRED>
<!ATTLIST titulacion anyo CDATA #REQUIRED>
<!ELEMENT experiencia-profesional (experiencia+)>
<!ELEMENT experiencia (puesto,empresa,anyo-inicio,anyo-fin)>
<!ELEMENT puesto (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT anyo-inicio (#PCDATA)>
<!ELEMENT anyo-fin (#PCDATA)>

=== cras974/Theory-and-explanatory/Basic programming languages/XML/Ejemplos/Representación de un Curriculum Vitae.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE cv SYSTEM "Dtd_cv_chulo.dtd">
<cv>
    <nombre> Miguel Ángel</nombre>
    <apellidos> García Cortés </apellidos>
    <f_nac> 06-01-2005 </f_nac>
    <residencia>
        <ciudad>Granada</ciudad>
        <pais>España</pais>
    </residencia>
    <contacto>
        <tlf>674235812</tlf>
        <correo>corre@gmail.com</correo>
        <linkedin>http://www.linkedin.com/ejemplo</linkedin>
    </contacto>
    <descripcion>Este es un curriculum de ejemplo</descripcion>
    <competencias>
        <competencia nivel="Alto" nombre="Diseño"/>
        <competencia nivel="Medio" nombre="Trabajo en equipo"/>
        <competencia nivel="Alto" nombre="Música"/>
    </competencias>
    <formacion>
        <titulacion nombre="Diseño industrial" centro="Colegio municipal de artes industriales de Kanazawa" anyo="2024"/>
        <titulacion nombre="Ingles" centro="Academia" anyo="2022"/>
    </formacion>
    <experiencia-profesional>
        <experiencia>
            <puesto>Diseñador de juegos</puesto>
            <empresa>Nintendo</empresa>
            <anyo-inicio>2020</anyo-inicio>
            <anyo-fin></anyo-fin>
        </experiencia>
    </experiencia-profesional>
</cv>
