=== cras974/Theory-and-explanatory/Basic programming languages/XML/Ejercicios/Facturas.dtd
<!ELEMENT factura (id,fecha,nombre,direccion,productos,total)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT productos (producto+)>
<!ELEMENT producto (unidades,IVA,subtotal)>
<!ATTLIST producto nombre CDATA #REQUIRED>
<!ATTLIST producto precio CDATA #REQUIRED>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT IVA (#PCDATA)>
<!ELEMENT subtotal (#PCDATA)>
<!ELEMENT total (#PCDATA)>

=== cras974/Theory-and-explanatory/Basic programming languages/XML/Ejercicios/Facturas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE factura SYSTEM "Facturas.dtd">
<factura>
    <id>1</id>
    <fecha>24-2-2026</fecha>
    <nombre>Pepe</nombre>
    <direccion>C/Ejemplo n1</direccion>
    <productos>
        <producto nombre="Pan" precio="1">
            <unidades>4</unidades>
            <IVA>10</IVA>
            <subtotal>4.2</subtotal>
        </producto>
        <producto nombre="Queso" precio="4">
            <unidades>1</unidades>
            <IVA>7</IVA>
            <subtotal>4.1</subtotal>
        </producto>
        <producto nombre="Botella de agua" precio="0.5">
            <unidades>10</unidades>
            <IVA>4</IVA>
            <subtotal>5.5</subtotal>
        </producto>
    </productos>
    <total>15</total>
</factura>
