=== cras974/Theory-and-explanatory/Basic programming languages/XML/Ejercicios/receta.dtd
<!ELEMENT receta (nombre,ingredientes,elaboración)>
<!ATTLIST receta dificultad (baja|media|alta) "media">
<!ATTLIST receta raciones CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>
<!ATTLIST ingrediente cantidad CDATA #IMPLIED>
<!ATTLIST ingrediente unidad CDATA #IMPLIED>
<!ELEMENT elaboración (#PCDATA)>

=== cras974/Theory-and-explanatory/Basic programming languages/XML/Ejercicios/receta.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE receta SYSTEM "receta.dtd">
<receta raciones="6" dificultad="media">
    <nombre>Tortilla de patatas</nombre>
    <ingredientes>
        <ingrediente cantidad="1" unidad="kilogramo">Patata</ingrediente>
        <ingrediente cantidad="8" unidad="unidades">Huevo</ingrediente>
        <ingrediente cantidad="1" unidad="unidad">Cebolla</ingrediente>
        <ingrediente>Sal</ingrediente>
    </ingredientes>
    <elaboración>
    Se pelan las patatas...
    </elaboración>
</receta>
